### ISSUE TITLE
Get rid of Laravel ;-)

### ISSUE THREAD

**Issue by ThomasLandauer** [ccharz/laravel-epc-qr#1]
Nice timing :-)

> Initial Release 3 days ago

You could easily refactor this to be universal, not just for Laravel:
1. Remove `Illuminate\Filesystem\Filesystem` from the constructor of `LaravelEpcQr`
2. Use it like this:
```php
use Ccharz\LaravelEpcQr\LaravelEpcQr;

$result = (new LaravelEpcQr())->amount(150)
    ->receiver('AT000000000000000000', 'ABCDATWW', 'Max Mustermann')
    ->note('test')
    ->purpose('AT12')
    ->text('Test Überweisungstext')
    ->build()
;
```
3. Rename it :-)
4. If that's really necessary (don't know, cause I'm not using Laravel), you could move the Laravel integration to a separate package, like https://github.com/endroid/qr-code-bundle for Symfony.

BTW: I would also rename all setters: `setIban()`, `setBic()`, ...

**Comment by ccharz** [comment]
Thank you for your feedback.

If you need a non-laravel version there is already a package on GitHub you can use https://github.com/smhg/sepa-qr-php
